### PR TITLE
Autotools build

### LINKED ISSUE #7: GNU autotools build
Are you open to having a GNU autotools based build? This would allow for the common build and install procedure `./configure && make && make install`.

I have a lot of experience with it and I can provide a PR if you're interested.

### PR DESCRIPTION
**Pull request by wookietreiber**
This is a complete autotools based build. Build instructions are updated in `README.md`. What is not in `README.md`, because it only concerns developers/maintainers, is that you now can create release tarballs via `make dist`.

The only thing missing, which was in the original `cpp/Makefile`, is the `VCFTOOLS_PCA` option. Is this still a thing? If so, I would add support for it via an `--enable-pca` option to `configure`. Let me know whether this should be added before you consider the pull request ready to be merged.

One other thing: I joined the `cpp` and `perl` directories in a `src` directory, because I personally think, this gives a repository more structure. If you are against this, this commit can of course be reverted.

If you have questions about any of this, feel free to ask.

Fixes #7.

### CODE REVIEW

**Comment by auton1** [comment]
This is awesome! Thanks for putting together.

The VCFTOOLS_PCA thing is definitely still required. This enables compilation of the (never publicised) PCA options, but requires LAPACK, so is turned off by default. 

Happy to have cpp and perl as subfolders of src.

Thanks again.

**Comment by sjackman** [comment]
:+1:

**Comment by auton1** [comment]
I have tested this, and like it. Will merge if we can get --enable-pca added.

**Comment by wookietreiber** [comment]
I think I am going to get `--enable-pca` done either today or tomorrow.

**Comment by wookietreiber** [comment]
The optional PCA feature is implemented now. Do you have a small test example I can use to test this? It should work like this:

1.  `./configure`, i.e. implicit `--disable-pca`, should print the "Cannot run PCA analysis." text of `variant_file_output.cpp`.
2.  `./configure --enable-pca` should do the PCA analysis.

I also fixed the man page help text as well as using the version that is in `configure.ac`. About the latter: if you bump version, you need only to modify the version string in `configure.ac` now and do `autoreconf` because the `PACKAGE_VERSION` is in the autoconf-generated `config.h`. I also used the `-SNAPSHOT` suffix to indicate that this is a build of the current git HEAD. Your release workflow could now look like this:

```
sed -i 's|VERSION-SNAPSHOT|VERSION|' configure.ac
git add configure.ac
git commit -m 'release version VERSION'
git tag -am 'release version VERSION' VERSION
autoreconf
./configure
make dist
# release the created tarball vcftools-VERSION.tar.gz on the web
sed -i 's|VERSION|NEXT_VERSION-SNAPSHOT|' configure.ac
git add configure.ac
git commit -m 'bump version to next SNAPSHOT'
git push
autoreconf
```

This workflow clearly differentiates having a tagged and released build from having a build that is made from cloning the git repository and building from that one.

I know other projects using the git sha in the SNAPSHOT version as well, e.g. `0.1.14-SNAPSHOT-$(git rev-parse HEAD)`. This is indeed very useful whenever you get a bug report because you will know the exact commit that has been used to build the product that has the bug. This makes it a lot easier to reproduce these reported issues.

**Comment by auton1** [comment]
I can confirm the PCA option now works. Thank you.

However, for the release workflow, I had a few issues. Apologies if these are obvious to fix, but I want to be 100% clear about how this works.

First, I think the sed command should be:

`sed -i -e 's|VERSION-SNAPSHOT|VERSION|' configure.ac`

Second, I get the following errors at the `autoreconf` stage of the release workflow:
```
configure.ac:14: error: required file './compile' not found
configure.ac:14:   'automake --add-missing' can install 'compile'
configure.ac:10: error: required file './install-sh' not found
configure.ac:10:   'automake --add-missing' can install 'install-sh'
configure.ac:10: error: required file './missing' not found
configure.ac:10:   'automake --add-missing' can install 'missing'
src/cpp/Makefile.am: error: required file './depcomp' not found
src/cpp/Makefile.am:   'automake --add-missing' can install 'depcomp'
autoreconf: /opt/local/bin/automake failed with exit status: 1
```

Third, don't I need a `./autogen.sh` before the `./configure`?

Thanks again for helping with this. If we can sort out what the release workflow should be, I'll merge this pull request.

**Comment by sjackman** [comment]
Use `autoreconf -i` (copy missing auxiliary files) to add the missing automake files. `autoreconf` does the same thing as `./autogen.sh`.

**Comment by auton1** [comment]
Ok, great. That works. Just to be clear, the release workflow is as follows.

<pre>
sed -i -e 's|v0.<b>X</b>.<b>XX</b>-SNAPSHOT|v0.<b>X</b>.<b>XX</b>|' configure.ac
git add configure.ac
git commit -m 'release version v0.X.XX'
git tag -am 'release version v0.X.XX' v0.X.XX
autoreconf -i
./configure
make dist
sed -i -e 's|v0.<b>X</b>.<b>XX</b>|v0.<b>Y</b>.<b>YY</b>-SNAPSHOT|' configure.ac
git add configure.ac
git commit -m 'bump version to next SNAPSHOT'
autoreconf
</pre>

I'm merging this pull request now. Thanks.

**Comment by wookietreiber** [comment]
Ah, I see the problem now. I already had the files generated by `autoreconf -i`. You need to run `autoreconf` with the `--install` or `-i` option only if you are on a fresh checkout and don't have these files like `compile`.

You are on the really safe side if you replace both `autoreconf` lines with `./autogen.sh`.

**Comment by auton1** [comment]
We had the following issue reported by a user:

>I have to install vcftools without root access (is this possible?). My autoconf didn't fit the minimum requirement. So, I upgraded autoconf and installed the newer version to a local directory:
/netapp/home/maka/bin/bin_201508/bin

>When I run ./autogen.sh, I got this error:

>$ ./autogen.sh
>sh: /usr/local/bin/autom4te: No such file or directory
>aclocal: /usr/local/bin/autom4te failed with exit status: 127
>autoreconf: aclocal failed with exit status: 127

>Is there anything I could adjust to work around this error?

Is there anything we can recommend here?

**Comment by wookietreiber** [comment]
I believe the autoconf requirement can be lowered. The current requirement is a result of my up to date Arch Linux and I created `configure.ac` via `autoscan` which automatically uses this high autoconf version requirement.

What is the autoconf version of the user? Then I can see if I can lower it to that version.

**Comment by auton1** [comment]
Apparently, it's `autoconf (GNU Autoconf) 2.63`

**Comment by wookietreiber** [comment]
I'll see what I can do, reporting back.

**Comment by wookietreiber** [comment]
Merge #14 and this should be resolved.

**Comment by auton1** [comment]
Thank you!

**Pull request merged**
